### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by MostafaRahgouy** [Rahgooy/emphasis#1]
The emphasis selection datasets contain dev, meta and train files. The training file contains **2741** sentences in which each sentence has less than 10 words, whereas, the development file contains **391** sentences.

The first step is related to how datasets behave which includes these subtasks:
* How many of the words are unique 
* What is the most frequent word
* What is the most frequent POS 
* What is the POS of the most frequent emphasis word
* What is the probability of sentences have multi_emphasis words

**Comment by MostafaRahgouy** [comment]
> The emphasis selection datasets contain dev, meta and train files. The training file contains **2741** sentences in which each sentence has less than 10 words, whereas, the development file contains **391** sentences.
> 
> The first step is related to how datasets behave which includes these subtasks:
> 
> * How many of the words are unique
> * What is the most frequent word
> * What is the most frequent POS
> * What is the POS of the most frequent emphasis word
> * What is the probability of sentences have multi_emphasis words


<b>The competition datasets(train-dev sets) added to [directory](https://github.com/Rahgooy/emphasis/tree/mostafa-dev/datasets).</b>

**Comment by HamedBabaei** [comment]
> The emphasis selection datasets contain dev, meta and train files. The training file contains **2741** sentences in which each sentence has less than 10 words, whereas, the development file contains **391** sentences.
> 
> The first step is related to how datasets behave which includes these subtasks:
> 
> * How many of the words are unique
> * What is the most frequent word
> * What is the most frequent POS
> * What is the POS of the most frequent emphasis word
> * What is the probability of sentences have multi_emphasis words

we add a data visualization jupyter-notebook to show how the dataset behaves as these subtasks wanted. Also, we got more ideas to detect the dataset behaviors we added them to this notebook too.
In summary, for now, we add Pie chart for the occurrence of POS's and a Scatter plot for occurrence and probability of words and also another Scatter plot for the occurrence and bold frequency of words. 
[here is the link to data visualization](https://github.com/Rahgooy/emphasis/blob/mostafa-dev/data_visualization.ipynb)

**Comment by Rahgooy** [comment]
I think this issue has been addressed, so I close it.
