### ISSUE TITLE
Investigate the importance of word frequencies in predicting the bold words

### ISSUE THREAD

**Issue by Rahgooy** [Rahgooy/emphasis#4]
From the analysis, we see some words have a high probability to be chosen as bold. We want to see how a good predictor would be a model that just makes use of word frequencies.
To do so, you need to :
- Split the train set to train/test. Using the train part, build the vocab. 
- For each word in the vocab find the probability of a word to be bold considering each annotation as a sample. Which leads to a vector of probabilities for all words in the vocab.
- Using this vector, assign each word in the sentence with their respective probabilities. 
- Report the performance of this model, on the train and the test split using the official evaluation metrics.

**Comment by MostafaRahgouy** [comment]
We created the model and we got the performance of this model. Below you can see the model's result. The "score" refers to overall score of the model. It goes without saying we used the competition's evaluation script.
```
score1:  0.4416058394160584
score2:  0.6185468451242829
score3:  0.6925698704839819
score4:  0.7298474945533769
-----------------------------
score:   0.620642512394425
```

**Comment by Rahgooy** [comment]
Awesome!
As I discussed with Mostafa, it would be nice to make three different report files (.md) for the overall, quotes and the other one. In each file, we will incrementally introduce new models and report their results with cross-validation.
In order to complete this issue, we need to:
- [x] Run the model for quotes, overall and the other one
- [x] Use cross-validation(5-fold should be enough)
- [x] Create the report files
- [x] Use cross-validation to see if stemming is good
- [x] Use CV to see if replacing the numbers with 0 would help

**Comment by MostafaRahgouy** [comment]
> We created the model and we got the performance of this model. Below you can see the model's result. The "score" refers to the overall score of the model. It goes without saying we used the competition's evaluation script.
> 
> ```
> score1:  0.4416058394160584
> score2:  0.6185468451242829
> score3:  0.6925698704839819
> score4:  0.7298474945533769
> -----------------------------
> score:   0.620642512394425
> ```

We ran the baseline model on the train set and we got interesting results. Below, you can reach them.
```
score1:  0.6329229366165071
score2:  0.7402101241642789
score3:  0.778173794976244
score4:  0.8056451612903226
-----------------------------
score:    0.739238004261838

**Comment by Rahgooy** [comment]
They are pretty high!

**Comment by HamedBabaei** [comment]
> They are pretty high!

Yes, Is that a good thing?

**Comment by Rahgooy** [comment]
In general, if you have high performance on training data and low performance on the test, it is bad because you may be overfitted to the train data. But, here we have good performance on the test. So, I think we haven't overfitted to the data. One reason for less accuracy in the test can be the new words that are not seen during training. And, having high scores on the train data shows that the model is able to capture the complexity of the task.

**Comment by MostafaRahgouy** [comment]
> Awesome!
> As I discussed with Mostafa, it would be nice to make three different report files (.md) for the overall, quotes and the other one. In each file, we will incrementally introduce new models and report their results with cross-validation.
> In order to complete this issue, we need to:
> 
> * [ ]  Run the model for quotes, overall and the other one
> * [ ]  Use cross-validation(5-fold should be enough)
> * [ ]  Create the report files
> * [ ]  Use cross-validation to see if stemming is good
> * [ ]  Use CV to see if replacing the numbers with 0 would help

Taher, there is a one thing we could not figure out. For "sparks" & "quotes" whether we should train our model on overall types of data(Spark & Quotes) or separately?

**Comment by HamedBabaei** [comment]
> In general, if you have high performance on training data and low performance on the test, it is bad because you may be overfitted to the train data. But, here we have good performance on the test. So, I think we haven't overfitted to the data. One reason for less accuracy in the test can be the new words that are not seen during training. And, having high scores on the train data shows that the model is able to capture the complexity of the task.

Great!

**Comment by Rahgooy** [comment]
> > Awesome!
> > As I discussed with Mostafa, it would be nice to make three different report files (.md) for the overall, quotes and the other one. In each file, we will incrementally introduce new models and report their results with cross-validation.
> > In order to complete this issue, we need to:
> > 
> > * [ ]   Run the model for quotes, overall and the other one
> > * [ ]   Use cross-validation(5-fold should be enough)
> > * [ ]   Create the report files
> > * [ ]   Use cross-validation to see if stemming is good
> > * [ ]   Use CV to see if replacing the numbers with 0 would help
> 
> Taher, there is a one thing we could not figure out. For "sparks" & "quotes" whether we should train our model on overall types of data(Spark & Quotes) or separately?

I meant training them separately.

**Comment by HamedBabaei** [comment]
> Awesome!
> As I discussed with Mostafa, it would be nice to make three different report files (.md) for the overall, quotes and the other one. In each file, we will incrementally introduce new models and report their results with cross-validation.
> In order to complete this issue, we need to:
> 
> * [x]  Run the model for quotes, overall and the other one
> * [ ]  Use cross-validation(5-fold should be enough)
> * [x]  Create the report files
> * [ ]  Use cross-validation to see if stemming is good
> * [ ]  Use CV to see if replacing the numbers with 0 would help

Taher, we performed cross-validation on bellow datasets to see whether stemming is good or not, we got results which show that stemming doesn't affect on WordFrequencyModel

```
datasets/train-train-split.txt
{1: 0.5366, 2: 0.6667, 3: 0.7264, 4: 0.7653, 'Overall': 0.6737}
----------------------------------------
datasets/q-train-train-split.txt
{1: 0.5265, 2: 0.6566, 3: 0.7161, 4: 0.7601, 'Overall': 0.6648}
----------------------------------------
datasets/s-train-train-split.txt
{1: 0.6236, 2: 0.7215, 3: 0.7776, 4: 0.8060, 'Overall': 0.7322}
----------------------------------------
```

**Comment by MostafaRahgouy** [comment]
> Awesome!
> As I discussed with Mostafa, it would be nice to make three different report files (.md) for the overall, quotes and the other one. In each file, we will incrementally introduce new models and report their results with cross-validation.
> In order to complete this issue, we need to:
> 
> * [x]  Run the model for quotes, overall and the other one
> * [x]  Use cross-validation(5-fold should be enough)
> * [x]  Create the report files
> * [x]  Use cross-validation to see if stemming is good
> * [x]  Use CV to see if replacing the numbers with 0 would help

``` 
datasets/train-train-split.txt`
{1: 0.5231,  2: 0.6668,  3: 0.7269,  4: 0.7666, 'Overall': 0.6710}
----------------------------------------
datasets/q-train-train-split.txt
{1: 0.5023,  2: 0.6530,  3: 0.7172,  4: 0.7640,  'Overall': 0.6591}
----------------------------------------
datasets/s-train-train-split.txt
{1: 0.6145,  2: 0.711,  3: 0.7774,  4: 0.7949, 'Overall': 0.7245}
```

As you see above, we did not get any eye_opening differences for replacing numbers with "0".

**Comment by Rahgooy** [comment]
I think we are done with this issue, so I close it.
Thanks for the hard work!
