### ISSUE TITLE
Investigate if conditional probabilities would help the model predictions

### ISSUE THREAD

**Issue by Rahgooy** [Rahgooy/emphasis#6]
A natural extension of our baseline model is to use the relation between the words to improve the predictions. In this issue, we want to investigate if the presence of a word in the sentence changes the probability of other words or not. To do so we need to:
- [x] Create the `P(bold_w_i|w_i, w_j)` matrix `P` where the diagonal would be the current probability vector `P(w)`. `P[i, j]` is calculated by dividing the number of `w_i` bold occurrences in sentences that contain both `w_i` and `w_j` by the total number of sentences that contain both(Please let me know if it doesn't make sense).
- [x] For visualization, plot the `P` matrix for high probability words. To do so, pick 50 top high-value pairs (i, j) from the matrix where `i != j`. Then, plot the matrix only for words that appeared in those pairs. The words will repeat in both axis and we have a grid in the plot the values are highlighted by color intensity.
- [x] Use P to find the scores. The score for word `w_j` in the sentence is calculated by averaging over `jth` row for the words in the sentence `S`. `Score = sum(P[j, k] for k in S)`

**Comment by Rahgooy** [comment]
Sure!
Let say we want to calculate `P[1,2]` which is the `P(w1|w2`). First, find the number of sentences that `w2` has occurred in (`n_w2`). Now, find the number of times `w1` is bold in those sentences  (`n_b_w1_w2`).  Finally, `P[1,2]` = `n_b_w1_w2/ n_w1`.

**Comment by MostafaRahgouy** [comment]
> Sure!
> Let say we want to calculate `P[1,2]` which is the `P(w1|w2`). First, find the number of sentences that `w2` has occurred in (`n_w2`). Now, find the number of times `w1` is bold in those sentences (`n_b_w1_w2`). Finally, `P[1,2]` = `n_b_w1_w2/ n_w2`.

Thanks, I got this section, but, how to create matrix of p?

**Comment by MostafaRahgouy** [comment]
We added the two first tasks to the data visualization file. The code needs to be more clear but we added to get a basic view about them.

**Comment by MostafaRahgouy** [comment]
We used WordConditionalModel for prediction. To see the results please go to the "results" directory. During the examination, we realized that the two models(`WordFrequency` and `WordConditional`) have the same order for each score(...). To clarify let's look at one of them.

| 1 | **WordFrequencyModel** | 0.4584 | 0.6219 | 0.6890 | 0.7295 | **0.6247** |
| 2 | **WordConditionalModel** | 0.4075 | 0.5576 | 0.6291 | 0.6716 | **0.5664** |

Also, as you see,  `score one`(`top k = 1`) has a lower score among all scores and models. It will be a big deal if the differences between our prediction and actual `top k = 1` are very high. In other words, types of errors play a vital role in improvement.
